name: CD - Entrega Contínua Docker

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publicar_imagem:
    name: Build e Push para Docker GitHub Hub
    runs-on: ubunt-latest


    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Login no docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build e push da publicar_imagem
        uses: docker/build-push-action@v5
        with:
          context:
          push: true

          tags: ${{secrets.DOCKER_USERNAME}}/kanpan-api:${{github.ref_name}}